name: CI

on:
  push:
    branches: [ main, setup/dev-tooling ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Test & Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Run format check
        run: bun run format:check

      - name: Run linting
        run: bun run lint

      - name: Run tests
        run: bun run test:coverage

      - name: Build project
        run: bun run build

      - name: Verify CLI works
        run: |
          bun run start --version
          bun run start --help

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        if: success()
        with:
          fail_ci_if_error: false
          verbose: true